### ISSUE TITLE
Keyboard shorcut for Eval

### ISSUE THREAD

**Issue by hiram-madelaine** [mfikes/replete#16]
In order to test Replete I use a wireless keyboard. Is it possible to add a shortcut to eval the form ?
cmd + enter

**Comment by mfikes** [comment]
That sounds cool. I've never delved into that part of the iOS SDK, but yeah, that would make things much easier.

**Comment by hiram-madelaine** [comment]
Great !
It would make sense to have access to the history with cmd+Up to be very efficient at testing.

**Comment by mfikes** [comment]
Added #18

**Comment by hiram-madelaine** [comment]
Thank you Mike ! If you need help, I would be pleased to learn Swift.

**Comment by mfikes** [comment]
@hiram-madelaine Absolutely! (I don't know Swift.) If you want to see if a keyboard shortcut can be hooked in, happy to take a PR!

**Comment by hiram-madelaine** [comment]
@mfikes I begin to learn the basics in order to feel compfortable with Swift. After that I will look into the keyboard part.

**Comment by mfikes** [comment]
@hiram-madelaine Awesome!

**Comment by kanaka** [comment]
For some point in the future, you might consider trying to read the form any time enter is pressed. If read results in a mismatched paren, bracket or curly error, then continue editing on the next line, otherwise, eval the form. I think that's a typical way that multiline entry is supported automatically in many REPLs. Just a thought.

**Comment by mfikes** [comment]
@kanaka yep. Your description might match Cursive, actually.

**Comment by mfikes** [comment]
@kanaka Yes, you are "right" IMHO with your suggestion. #27 entered. Thanks!
